### ISSUE TITLE
Not working on TC26

### ISSUE THREAD

**Issue by EArminjon** [circus-kitchens/flutter_datawedge#12]
Hello,

We have identified an issue with our customers. This package seems to not work on TC 26 devices. We have tested that with the package example.

We use flutter 3.3.4 and flutter_datawedge 1.2.0.

**Comment by felixwoestmann** [comment]
Hello, we don't have any TC26 devices to test your issue. Could you maybe provide any error messages that were emitted or debug logs?

**Comment by EArminjon** [comment]
Will provide that next week, need to contact my customers.

**Comment by LenhartStephan** [comment]
I've just tested the example app on a TC26 and I've not encountered any problems.

**Comment by EArminjon** [comment]
I will provide the package example to my customer so, ty for the feedback. I will come back soon with news.

**Comment by EArminjon** [comment]
@felixwoestmann  is it possible to emulate zebra scan process with a simple android studio emulator and ADB ?

**Comment by felixwoestmann** [comment]
@EArminjon yes it is possible to trigger the code on the dart side of things manually:

adb -s emulator-5554 shell am broadcast 
-a com.circuskitchens.flutter_datawedge.SCAN_EVENT 
-e com.symbol.datawedge.source scanner 
-e com.symbol.datawedge.label_type LABEL-TYPE-QRCODE
-e com.symbol.datawedge.data_string thisIsData

Simulates a QR Code containing thisIsData send to emulator-5554
You also have to replace -a com.circuskitchens.flutter_datawedge.SCAN_EVENT with -a <your_package_name>.SCAN_EVENT

**Comment by EArminjon** [comment]
(I will soon have a TC26 on my hand, i keep this issue open and will send you info as soon as possible)

**Comment by EArminjon** [comment]
Not yet my enterprise got trouble with ordering Zebra TC26 (we got one without the scanner... ty Zebra...)
I still wait to receive the one with the scanner, issue still open sorry :/ !

Will update you as soon as possible.

**Comment by ducchungtx** [comment]
With me, the Zebra ET40 is not working, but the TC26 is working well. Do you have any ideals?

**Comment by james-rich** [comment]
The devices are currently running Android 11 and Datawedge 11.3.28.

**Comment by EArminjon** [comment]
Hello,

Sorry for the huuuuuuge delay. After many weeks of investigation the package seems to work well on TC26. We identified that something in our app collide with this package. We are still working an it and will open a new ticket if something need to be done here. 

Sorry for the delay !

**Comment by ducchungtx** [comment]
> I am not completely sure, since I am lacking a proper device to test it. But it could be due to the Tablet being on Android 14.
> 
> `• Starting with Android 14, all DataWedge intent APIs are secured in controlled mode; use of DataWedge intent APIs is **restricted to apps whitelisted by administrators**. Optionally, administrators can turn off controlled mode if DataWedge intent APIs need to be used by any application. See [Control Access to DataWedge intent APIs](https://zebra-techdocs-archive.netlify.app/datawedge/latest/guide/programmers-guides/secure-intent-apis/).`
> 
> source: https://zebra-techdocs-archive.netlify.app/datawedge/latest/guide/about/
> 
> Can you maybe look up the Android version as well as the Datawedge version in the Datawedge app?

Currently, the tablet is running Android 11. I don't know why, but the old version of this library is working with this tablet (Zebra ET40).
