### ISSUE TITLE
Profile resets each time app is opened

### ISSUE THREAD

**Issue by james-rich** [circus-kitchens/flutter_datawedge#22]
I am having an issue where the profile resets each time the app is opened meaning all decoders that was enabled are reset to the default and I have to go into datawedge and manually enable them again. 

is there a way to enable the decoders from dart? or a way to stop a new profile being created if one already exists?

**Comment by james-rich** [comment]
The devices are currently running Android 11 and Datawedge 11.3.28.

**Comment by felixwoestmann** [comment]
Thank you for your input. Currently we are creating a new profile every time FlutterDatawedge is instantiated, this seems to overwrite the old profile. We will implement that if a profile with the given name already exists, it will not be overwritten.

**Comment by james-rich** [comment]
Is there any way to stop this from happening or can I send an intent to enable the decoder that keeps getting disabled?

**Comment by felixwoestmann** [comment]
The following branch: [skip_profile_creation_option](https://github.com/circus-kitchens/flutter_datawedge/tree/skip_profile_creation_option) contains changes which I think will fix the issue.

flutter_datawedge won't create a profile and configure it during initialisation, the should fix the issue of the profile resetting when the app is opened. 

I migrated that functionality to the function `createDefaultProfile`.
Additionally the active profile can be fetched using `requestActiveProfile` and `waitForActiveProfile` as well as a list of all installed profiles with `requestProfiles` and `waitForProfiles`.

Please have a look if this changes will fix the issue, then we will release it on pub.dev.

```
flutter_datawedge:
    git:
      url: git@github.com:circus-kitchens/flutter_datawedge.git
      ref: skip_profile_creation_option
```

**Comment by felixwoestmann** [comment]
@james-rich We just released the Branch to pub.dev as a PreRelease. https://pub.dev/packages/flutter_datawedge/versions/3.0.0-dev.1
