### ISSUE TITLE
Provide ability to use INTENT ACTION to simulate zebra device

### ISSUE THREAD

**Issue by noga-dev** [circus-kitchens/flutter_datawedge#23]
Since I don't own a zebra device and need to test what I'm working on, it would be good if we could use similar API provided by Zebra via https://developer.zebra.com/blog/test-your-zebra-scanning-application-emulator

They provide a test app that has an INTENT we can call with ADB: https://github.com/darryncampbell/DataWedge-API-Exerciser/blob/darryncampbell_repo_backup/app/src/main/AndroidManifest.xml

**Comment by t-unit** [comment]
You should be able to use intents with the library as well. E.g. we testing with a command similar to:

```bash
adb -s your-device \
    shell am broadcast \
        -a com.circuskitchens.x.SCAN_EVENT \
        -e com.symbol.datawedge.source scanner \
        -e com.symbol.datawedge.label_type LABEL-TYPE-QRCODE \
        -e com.symbol.datawedge.data_string https://x.circuskitchens.com/y/z
```
