### ISSUE TITLE
Is there a way to detect if the datawedge is present?

### ISSUE THREAD

**Issue by mbalmer** [circus-kitchens/flutter_datawedge#44]
Is there a way to detect if the datawedge is present, i.e. if we are running on a Zebra device?

**Comment by t-unit** [comment]
There is not way to directly detect it with this package. 


We rely on [Device Info Plus](https://pub.dev/packages/device_info_plus) for that.

```dart
final deviceInfo = await DeviceInfoPlugin().androidInfo;
final shouldInitializeDatawedge = deviceInfo.brand == 'Zebra';
```

By all means not perfect, but does the trick for us

**Comment by mbalmer** [comment]
An ugly hack :) But well, it does the job, thanks.
