### ISSUE TITLE
updateProfile not found

### ISSUE THREAD

**Issue by alessandroToninelli** [circus-kitchens/flutter_datawedge#52]
on 3.0.0 updateProfile is not found. I need to call this methos to set PLUGIN_NAME:Barcode for reading ean8 and i2of5. Otherwise the default profile can't read this type of barcode

**Comment by felixwoestmann** [comment]
@alessandroToninelli We released the `updateProfile` method introduced by [this PR](https://github.com/circus-kitchens/flutter_datawedge/pull/49) just now as a pre release [v3.1.0-dev](https://pub.dev/packages/flutter_datawedge/versions/3.1.0-dev.1).

Please have a look at this.

**Comment by felixwoestmann** [comment]
@alessandroToninelli Is this Issue solved?

**Comment by alessandroToninelli** [comment]
yes thank u
