### ISSUE TITLE
Execution failed for task ':flutter_datawedge:compileDebugKotlin'.

### ISSUE THREAD

**Issue by welcome14** [circus-kitchens/flutter_datawedge#54]
Hi, i have this issue when i run the debug mode

`* What went wrong:
Execution failed for task ':flutter_datawedge:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 46s`

how i resolve it ?

**Comment by t-unit** [comment]
@welcome14  can you please provide us with more information. 

1. What version of this library are you using? 
2. What is your gradle setup inside your project? Especially, what Kotlin version is setup in your project?
3. Please provide debug logs, as just your posted message does not contain any useful content.

**Comment by welcome14** [comment]
androidGradlePluginVersion=7.3.0

plugins {
    id "dev.flutter.flutter-plugin-loader" version "1.0.0"
    id "com.android.application" version "7.3.0" apply false
    id "org.jetbrains.kotlin.android" version "1.7.10" apply false
}
I have installed the latest versione of this library.

**Comment by welcome14** [comment]
Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.

**Comment by t-unit** [comment]
@welcome14 can you try updating your app to gradle `8` and kotlin `1.9`. You can have a look at our [example](https://github.com/circus-kitchens/flutter_datawedge/blob/main/example/android/build.gradle).

**Comment by t-unit** [comment]
I'm closing this issue. @welcome14 feels free to re-open in this issue this exists

**Comment by stan-at-work** [comment]
> I'm closing this issue. @welcome14 feels free to re-open in this issue this exists

It seems that your build.gradle file was created some time ago. In newer Flutter projects, the build.gradle file no longer includes ext.kotlin_version or classpath 'com.android.tools.build:gradle:8.1.1'.

Could you update the file to reflect the latest Flutter recommendations, or provide an example of how to configure it with the recent changes?

My build.gradle: (android -> build.gradle)

```
allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
```

and my 2nd build.gradle: (android -> app -> build.gradle)

```
plugins {
    id "com.android.application"
    id "kotlin-android"
    // The Flutter Gradle Plugin must be applied after the Android and Kotlin Gradle plugins.
    id "dev.flutter.flutter-gradle-plugin"
}

android {
    namespace = "..."
    compileSdk = flutter.compileSdkVersion
    ndkVersion = flutter.ndkVersion

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_1_8
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId = "...."
        targetSdk = flutter.targetSdkVersion
        minSdk = flutter.minSdkVersion
        versionCode = flutter.versionCode
        versionName = flutter.versionName
        manifestPlaceholders += [
            'appAuthRedirectScheme': '...'
        ]
    }

    signingConfigs {
        release {
            storeFile System.getenv("...") ? file(System.getenv("...")) : null
            storePassword System.getenv("...")
            keyAlias System.getenv("...")
            keyPassword System.getenv("...")
        }
    }

    buildTypes {
        release {
            signingConfig = signingConfigs.debug
        }
    }
}

flutter {
    source = "../.."
}

```
