### ISSUE TITLE
Invalid argument(s): `PLUGIN_READY` is not one of the supported values: WAITING, SCANNING, IDLE, DISABLED

### ISSUE THREAD

**Issue by islamoktay** [circus-kitchens/flutter_datawedge#63]
Hello,

I am getting this error from Crashlytics. I think this state needs to be handled also:

> Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Invalid argument(s): `PLUGIN_READY` is not one of the supported values: WAITING, SCANNING, IDLE, DISABLED
       at .$enumDecode(enum_helpers.dart:83)
       at ._$$_ScannerStatusFromJson(scanner_status.g.dart:11)
       at new _$_ScannerStatus.fromJson(scanner_status.freezed.dart:114)
       at ._$ScannerStatusFromJson(scanner_status.freezed.dart:18)
       at new ScannerStatus.fromJson(scanner_status.dart:15)

**Comment by t-unit** [comment]
Thank you for reporting this. I will have a look at it later this week

**Comment by t-unit** [comment]
@islamoktay when and how does this happen for you? According to the [documentation](https://techdocs.zebra.com/datawedge/latest/guide/api/registerfornotification/) `PLUGIN_READY` is part of `WORKFLOW_STATUS`. But somehow it is getting triggered with `SCANNER_STATUS`.

We can be more verbose and ignore not expected values. But it would be nice to understand why this happens

**Comment by islamoktay** [comment]
@t-unit hi again,

I am not sure when this happens. I could not catch this while debugging.
I saw it in the crashlytics and I looked into the code and saw that it is not being handled.

**Comment by islamoktay** [comment]
@t-unit hello, is there any update about this. Thank you :)

**Comment by islamoktay** [comment]
I coded my own package. Thanks to long return. Thank you
